/**
 * Canvas visual configuration.
 * The renderer in visuals.js should only consume values from here.
 */

const palette = {
  background: '#050505',
  backgroundSoft: '#0A0A0A',
  haze: '#8C9095',
  silver: '#D8DDE3',
  white: '#FFFFFF',
  graphite: '#6D7278',
  charcoal: '#2E3135',
  grid: '#34373B',
};

export const VISUALS_CONFIG = {
  meta: {
    version: '2026-05-09-rewrite-v4',
  },

  palette,

  stage: {
    centerXRatio: 0.52,
    centerXMin: 180,
    centerXRightPadding: 240,
    centerYRatio: 0.44,
    orbRadiusScale: 0.118,
    orbRadiusMin: 88,
    orbRadiusMax: 136,
    waveWidthScale: 1.02,
    waveWidthMax: 980,
    floorWidthScale: 0.92,
    pulseDecay: 0.88,
    pulseGain: 0.18,
  },

  background: {
    nodeCount: 14,
    areaWidthScale: 0.96,
    areaHeightRatio: 0.66,
    areaTopRatio: 0.06,
    driftX: 0.00012,
    driftY: 0.00009,
    radiusMin: 0.9,
    radiusRange: 1.1,
    linkDistance: 156,
    linkAlpha: 0.08,
    glowRadiusScale: 5.5,
    mistYRatio: 0.40,
    mistInnerRadiusScale: 0.04,
    mistOuterRadiusScale: 0.82,
    mistAlpha: 0.06,
    silverStop: 0.26,
    silverAlpha: 0.035,
    beamAlpha: 0.045,
    beamYRatio: 0.42,
  },

  audio: {
    lowRange: [0.02, 0.10],
    midRange: [0.10, 0.34],
    highRange: [0.34, 0.78],
    analyser: {
      fftSize: 1024,
      minDecibels: -92,
      maxDecibels: -18,
      smoothingTimeConstant: 0.86,
    },
  },

  grid: {
    columns: 6,
    rows: 8,
    topOffset: 22,
    bottomOffset: 34,
    columnSpacing: 58,
    depthSpacing: 116,
    rowCurvePower: 1.62,
    lineWidth: 1,
    axisWidth: 1.05,
    fillAlpha: 0.016,
  },

  waves: {
    segments: 160,
    envelopeBase: 0.30,
    envelopePeak: 0.70,
    lensFalloff: 0.082,
    lensFrequency: 10,
    lensSpeed: 1.15,
    centerLineBackAlpha: 0.05,
    centerLineFrontAlpha: 0.12,
    centerLineBackWidth: 0.7,
    centerLineFrontWidth: 0.8,
    lines: [
      {
        color: 'white',
        offsetY: 0,
        phase: 0.0,
        speed: 0.82,
        frequency: 8.6,
        detailFrequency: 15.5,
        baseAmplitude: 13,
        midGain: 18,
        detailAmplitude: 4,
        highGain: 8,
        audioBase: 10,
        audioGain: 10,
        idleAmplitude: 0.16,
        frontLens: 7,
        backLens: -2,
        envelopeScale: 0.54,
        frontAlpha: 0.78,
        backAlpha: 0.24,
        frontWidth: 1.65,
        backWidth: 1.0,
        frontShadowAlpha: 0.22,
        backShadowAlpha: 0.08,
        frontShadowBlur: 10,
        backShadowBlur: 4,
      },
      {
        color: 'silver',
        offsetY: -5,
        phase: 0.45,
        speed: 0.76,
        frequency: 7.2,
        detailFrequency: 13.4,
        baseAmplitude: 9,
        midGain: 14,
        detailAmplitude: 3,
        highGain: 6,
        audioBase: 8,
        audioGain: 8,
        idleAmplitude: 0.12,
        frontLens: 5,
        backLens: -2,
        envelopeScale: 0.50,
        frontAlpha: 0.54,
        backAlpha: 0.16,
        frontWidth: 1.1,
        backWidth: 0.8,
        frontShadowAlpha: 0.14,
        backShadowAlpha: 0.05,
        frontShadowBlur: 8,
        backShadowBlur: 3,
      },
      {
        color: 'graphite',
        offsetY: 5,
        phase: -0.38,
        speed: 0.88,
        frequency: 9.5,
        detailFrequency: 17.2,
        baseAmplitude: 8,
        midGain: 12,
        detailAmplitude: 2.5,
        highGain: 5,
        audioBase: 7,
        audioGain: 6,
        idleAmplitude: 0.10,
        frontLens: 4,
        backLens: -1.5,
        envelopeScale: 0.48,
        frontAlpha: 0.44,
        backAlpha: 0.12,
        frontWidth: 0.95,
        backWidth: 0.72,
        frontShadowAlpha: 0.10,
        backShadowAlpha: 0.04,
        frontShadowBlur: 6,
        backShadowBlur: 2,
      },
    ],
  },

  orb: {
    pulseScale: 0.05,
    auraScale: 2.2,
    auraAlpha: 0.07,
    shellInnerAlpha: 0.10,
    shellMidAlpha: 0.05,
    shellOuterAlpha: 0.01,
    shellStrokeAlpha: 0.34,
    shellStrokeWidth: 1.1,
    shellShadowAlpha: 0.14,
    shellShadowBlur: 10,
    highlightWidth: 0.9,
    highlightAlpha: 0.44,
    contourCount: 2,
    contourAlpha: 0.14,
    contourWidth: 0.75,
    coreScale: 0.24,
    coreAlpha: 0.18,
    flareHScale: 2.1,
    flareVScale: 1.2,
    flareAlpha: 0.24,
    flareWidth: 1.0,
  },

  meters: {
    primaryXFactor: 1.82,
    primaryYOffsetFactor: -0.10,
    secondaryXFactor: 1.66,
    secondaryYOffsetFactor: 0.62,
    bars: 10,
    spacing: 7,
    stepY: 6,
    lineWidth: 1.25,
    sampleStart: 0.18,
    sampleSpan: 0.55,
    sampleSpread: 2,
    heightBase: 8,
    heightScale: 42,
    opacity: 0.15,
    idleBase: 0.10,
    idleAmplitude: 0.05,
    idleSpeed: 1.6,
    idleFrequency: 7,
  },

  idle: {
    lowBase: 0.05,
    lowWave: 0.014,
    lowSpeed: 1.2,
    midBase: 0.045,
    midWave: 0.010,
    midSpeed: 0.85,
    midPhase: 1.2,
    highBase: 0.038,
    highWave: 0.008,
    highSpeed: 1.5,
    highPhase: 2.4,
    waveformA: 1.8,
    waveformAFrequency: 10,
    waveformAAmplitude: 0.14,
    waveformB: 2.7,
    waveformBFrequency: 17,
    waveformBAmplitude: 0.045,
  },
};

export const VISUALS_COLORS = {
  haze: hexToRgb(palette.haze),
  silver: hexToRgb(palette.silver),
  white: hexToRgb(palette.white),
  graphite: hexToRgb(palette.graphite),
  charcoal: hexToRgb(palette.charcoal),
  grid: hexToRgb(palette.grid),
};

function hexToRgb(hex) {
  const normalized = hex.replace('#', '');
  const value = normalized.length === 3
    ? normalized.split('').map((char) => char + char).join('')
    : normalized;
  const int = Number.parseInt(value, 16);
  return [
    (int >> 16) & 255,
    (int >> 8) & 255,
    int & 255,
  ];
}
